movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name = 'movieapp'
urlpatterns =[
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path("add/",views.add_movie,name="add_movie"),
    path("update/<int:id>/",views.update,name="update"),
    path("delete/<int:id>/",views.delete,name="delete"),
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls")),
]
if settings.DEBUGS:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.


class Movie(models.Model):
    objects = None
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to="galary")

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect

from .forms import MovieForm
from .models import Movie

# Create your views here.


def index(request):
    movie = Movie.objects.all()
    context = {"movie_list": movie}
    return render(request, "index.html", context)


def details(request,movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request,"details.html", {"movie": movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get("name")
        year = request.POST.get("year")
        desc = request.POST.get("desc")
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")


def update(request,id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request,"edit.html",{"form":form,"movie":movie})


def delete(request,id):
    movie= Movie.objects.get(id=id)
    return render(request,"delete.html")

movieproject/templates/add.html
{% extends "base.html" %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <input type="text" name="desc" placeholder="enter movie description">
    <input type="text" name="year" placeholder="enter movie year">
    <input type="file" name="img" >
    <input type="submit">
    {% endblock %}
</form>

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MOVIES DETAILS</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    MOVIE CENTER
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form>
    {% csrf_token %}
    Are you sure,to delete thos movie?
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
   <div class="row">
      <div class="col-md-6">
         <img src="{{movie.img.url}}" width="300" height="300">
      </div>
      <div class="col-md-6" id="row-md-3">
         <h2 style="color:violet;"> {{movie.name}} </h2>
        <h4>{{movie.desc}}</h4>
        <h6>{{movie.year}}</h6>

         <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}"> UPDATE </a>
         <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}"> DELETE </a>
      </div>
   </div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">

            <div class="card" style="width: 17rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="300" height="250">
                    <div class="card-body">

                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{i.des}}</p>
                        <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">DETAILS</a>
                    </div>
            </div>


        </div>
        {% endfor %}


    </div>
</div>
<div style="text-align :center;"> <br> <br><a class="btn btn-warning" href="{% url 'movieapp:add_movie'  %}">add a movie</a></div>
{% endblock %}